### ISSUE TITLE
Zoom in/out buttons for fine grained zoom control

### ISSUE THREAD

**Issue by bestchai** [RepoGrams/RepoGrams#101]
Add a + and - zoom-in/out buttons to allow users to control zoom at finer granularity. Place somewhere next to the zoom slider. Slider and buttons should correspond.

**Comment by daniboy** [comment]
Add the buttons like so:

![untitled](https://cloud.githubusercontent.com/assets/1839738/7713809/04f18a02-fe2f-11e4-9424-e1878992d7a7.png)
