### ISSUE TITLE
Update the RepoGrams URL according to the settings of the current page

### ISSUE THREAD

**Issue by mpalyart** [RepoGrams/RepoGrams#103]
That'd be great to have something like that as URL:

http://repograms.net?repos=elastic/elasticsearch,apache/maven&metrics=author_xp&group_by=metric&block_length_mode=linear&normalization=globally&zoom=6&scolling_bar_pos=28

so you could just send the URL to someone and that would load it on their machine and have the exact same view as you. That could also be a nice way to reference a particular configuration.

**Comment by bestchai** [comment]
The URLs would get huge -- we also include all commits hidden from view, and other attributed will come up (e.g., imagine 10 repos in that URL).

The json feature solves this already, too. So, I would say that this should be at lowest priority.

**Comment by daniboy** [comment]
Closing this issue for now.
