### ISSUE TITLE
No scrollbars appearing

### ISSUE THREAD

**Issue by murphygc** [RepoGrams/RepoGrams#41]
Environment: Mac OSX, Chrome and Safari
Project: https://github.com/tschellenbach/Django-facebook

For metrics like "Most edit file" no scrollbar is appearing when block length is commit size or fixed width.

This is also true for other metrics.

**Comment by bestchai** [comment]
@murphygc can you check the scrollbars issue again?

On Yosemite+Chrome a scrollbar appears when I drag across the main repograms view (too bad the scrollbar is not shown by default, but I think that's an OSX issue?).

**Comment by bestchai** [comment]
Closing. But, the mac scroll bar not being immediately visible might need its own issue (e.g., we may need to add text at the bottom that notes that the view is scrollable).
