### ISSUE TITLE
[Block length] Semantics not transparent enough especially Fit to Screen

### ISSUE THREAD

**Issue by mpalyart** [RepoGrams/RepoGrams#46]
The semantics of the different types of block length is not explicit enough. I don't think that a new Repograms user understand the differences between the 3 types of bloc length and especially that the Fit to Screen view cannot be used to compare block lengths between projects since they all have different ratios for the number of pixel by line of code modified.

A short description or a tool-tip explaining how the block length is computed could really be usefull
When the Fit to Screen view is selected a warning should state that block lengths are not comparable

**Comment by daniboy** [comment]
Replaced by #91.
