### ISSUE TITLE
[Block length] New Type, Another Approach for the Fit To Screen

### ISSUE THREAD

**Issue by mpalyart** [RepoGrams/RepoGrams#47]
As explained in the issue #46 the current Fit to Screen approach for computing block length is misleading. However this view is pretty useful to get an overview of the repository so I propose a fourth approach for computing block length that could still offer that feature. Instead of trying to fit the version based on the churn we could try to fit the version based on the fixed width ?

**Comment by daniboy** [comment]
Replaced by #91.
