### ISSUE TITLE
Show metric/block length selection dialogue on button hover

### ISSUE THREAD

**Issue by bestchai** [RepoGrams/RepoGrams#64]
Related to #62, another way to improve metric/block length selection is to show the selection dialogue on hover (i.e., hovering over the button/text), instead of showing it on click. In addition, the dialogue could disappear when the pointer exits the dialogue (instead of implementing this with a cancel button).

**Comment by daniboy** [comment]
@bestchai do you think this is still relevant? The selection windows became more complex since this issue was first created

**Comment by bestchai** [comment]
I do think there are still too many clicks to get to some of the menus. But, the other features are more important. I'm closing this one and if it comes up again as a pain point, then we can reopen.
