### ISSUE TITLE
Support a private SSH key

### ISSUE THREAD

**Issue by daniboy** [RepoGrams/RepoGrams#81]
For the class study we want to support private github repositories using a private SSH key. If possible, multiple keys should work, but don't bother if it's a lot more work compared to a single SSH key.
There's no need for a UI for this, we can upload the SSH key to the deployment and build the docker image with the key file included.

**Comment by daniboy** [comment]
I keep getting a "This transport isn't implemented" error, despite the documentation of pygit2 claiming that they support SSH. I'm suspecting this might be a missing dependency issue but I couldn't figure out how you handle dependencies for the Python part. Can you help solve this?

I was thinking that the Python app can check for the existence of a "ssh-key" directory, and if it then use its contents for all SSH requests (i.e. non-HTTP(S) requests)
(+add the "ssh-key" directory to the .gitignore file)

**Comment by Inkane** [comment]
This requires creating a credentials object and passing it to the fetch and clone_repository methods in scripts/githelpers.py. I can look into this tomorrow.

**Comment by daniboy** [comment]
I tried creating this credentials object and passing it, but it gave me the above warning ("This transport isn't implemented"...

**Comment by daniboy** [comment]
@Inkane any updates on this?

**Comment by Inkane** [comment]
The version which we use in the docker file (from some PPA)  does not seem to be build against OpenSSH. Therefore the ssh support is missing; we need to find some other provider for  the library, or build it when the docker file is created.

**Comment by bestchai** [comment]
Hi Fabian, can you take a look into adding ssh support to the docker file? It seems that once this support is there, it won't be too difficult to finish off the issue.
