### ISSUE TITLE
Title being blocked 

### ISSUE THREAD

**Issue by whitecat** [RepoGrams/RepoGrams#86]
![screen shot 2015-04-08 at 3 31 36 pm](https://cloud.githubusercontent.com/assets/122229/7127521/53ead420-e1fa-11e4-9b6e-4868c5f942a5.png)

For long titles they are over lapped by the metric bar.

**Comment by daniboy** [comment]
I tried fixing this before but the way the elements are laid out on the screen makes it a difficult problem. On the bright side, if you hover over the name it will show the full name in a tooltip.

I see two possible solutions to this:
1) hammer it until we can get three-dots to appear at the end of the name
2) do a fade-to-white on the right edge. I think that would be easier to achieve
![untitled](https://cloud.githubusercontent.com/assets/1839738/7167306/d7632392-e368-11e4-925b-59e9be4d94f8.png)

**Comment by whitecat** [comment]
I like the "..." idea.

**Comment by daniboy** [comment]
I like it too, but it's harder than you think :)

**Comment by bestchai** [comment]
fade-to-white idea is fine; easy is good.

**Comment by daniboy** [comment]
Should be fixed now. @bestchai @whitecat care to try it and let me know?

**Comment by bestchai** [comment]
Looks great. The tooltip takes a while to appear, though. Is this something you control?

**Comment by daniboy** [comment]
No, that's a browser or OS setting.

**Comment by bestchai** [comment]
Okay, then I think it's fine to leave as is.
