### ISSUE TITLE
Feature request: Hide large commits

### ISSUE THREAD

**Issue by whitecat** [RepoGrams/RepoGrams#88]
There should be a way to ignore large commits.
Students sometimes upload large text files or frameworks that are huge and  make finding smaller more significant changes possible.

Look at project
https://github.com/CPSC310-2014W2/Chitoge.git

Use the metric: "Commit Author"
Also recommend using Browse Length: "lines changed"
there are about 6 commits larger than 8k lines of code. 

It would be nice to ignore these types of commits. They remind me of bills getting passed in the USA. Maybe they have something important but 99% of it is just crap that has nothing to do with the actual bill.

**Comment by daniboy** [comment]
We discussed a cap on commit block width in the past and reached the conclusion that it will be very confusing to users, I have another idea which might solve this, see issue #91.

**Comment by whitecat** [comment]
I don't want a cap. I would like to actually ignore commits of a certain size. Kinda like remove outliers. I agree cap does not make sense.

**Comment by daniboy** [comment]
As discussed in the meeting: we'll add a "hide this commit" button to the popup modal that opens when you click a commit block

**Comment by daniboy** [comment]
@whitecat @bestchai check out the staging server, you can hide individual commits from the popup window.
There's no import/export support yet (I'll start working on #96 tomorrow) but this change requires a large part of the work that I was planning on doing with #91 so I started working on it as well.

**Comment by daniboy** [comment]
http://repograms.net:8888/

**Comment by bestchai** [comment]
This works well for me, looks great! The fact that it adjusts instantly is neat.

One thing might be helpful is to add a bit to the repo names to indicate whether any commits in the repo timeline are hidden (not which ones, just that some are hidden). Something like a star at the end of the repo name is sufficient, with a footnote grey text (or project name hover) to explain that "Some commits are hidden from view for this repository timeline" or similar. I'm okay with pushing this into a different issue, too.

**Comment by daniboy** [comment]
I was thinking of adding an icon to the top panel that would indicate hidden commits, and clicking on that icon will reveal which commits were hidden and will let you unhide them. It wouldn't be too much work to add this.

**Comment by bestchai** [comment]
That would work great. I think you should make it as simple as possible -- i.e., list hash ids that were hidden per repo, and allow the user to unhide each one.

**Comment by daniboy** [comment]
Added the unhide feature: http://repograms.net:8888/
@bestchai @whitecat check that it doesn't break anything?

**Comment by bestchai** [comment]
Looks great, doesn't break anything on my end.
