### ISSUE TITLE
Feature Request: Ignore some metrics in deployment

### ISSUE THREAD

**Issue by whitecat** [RepoGrams/RepoGrams#89]
For 310 in the summer can we ignore some of the metics.
Languages in commit,
Branches used,
Number of Branches
Pom Files
Merge indicator

I don't think any of these are pertinent to the class.

**Comment by daniboy** [comment]
This is a deployment option, once you provide us with your public SSH key and we allocate a server for the study I can show you how to modify and deploy your instance.
