### ISSUE TITLE
Modify block length to have a grid of 2×3 modes instead of the current 3 modes

### ISSUE THREAD

**Issue by daniboy** [RepoGrams/RepoGrams#91]
We want to modify the block length screen to have a grid of 2×3 modes as follows:

mode | Fixed | Linear | Logarithmic
---- | ----- | ------ | ---------
Comparable | [1] | [2] | [3]
Incomparable | [4] | [5] | [6]

Modes 1, 2, and 5 as they exist now.

Mode 1 (Fixed/Comparable) will be modified so that all commit blocks will have the same width, and that width will be normalized so that the project with the largest number of commits will take 100% of the available width and the rest of the projects will match up to that.

Mode 4 (Fixed/Incomparable) will normalize each project to taken 100% of the available width. The commit block length for each project will be different.

Mode 3 (Logarithmic/Comparable) will take the churn and set the width of each block to be a logarithmic scale: width = ln(churn) or log_10(churn) or log_2(churn) [not sure which is the best choice here]. Then after calculating all the block widths, normalize so that the biggest project will take 100% of the available width and normalize the remaining projects to match.

Mode 6 (Logarithmic/Incomparable) same as mode 3 but all projects get normalized to take 100% of the available width.

The logarithmic scale is intended to take the focus off of the massive refractoring commits, or when huge binary or text files get added. We still want to show that they're there, but we don't want them to be so large (as they are with the existing linear model) that the other commits get completely eclipsed.

**Comment by mpalyart** [comment]
Looks nice. Regarding the names for the modes. "Comparable" and "Incomparable" are rather properties (consequences) of the modes than the actual mode itself (behavior). That'd be more something like: packed/compact mode vs extended mode

**Comment by bestchai** [comment]
I think comparable/incomparable are the critical properties of the mode, so they make sense to me as labels in the table. Packed/compact doesn't convey what the mode is actually good for.

Another nice feature of this table is that it allows us to present other, non-churn, based block lengths to the user (e.g., block representing number of files modified in the commit).

**Comment by mpalyart** [comment]
That was my exactly my point it's only a property of the mode and an important one (that's why I thought it was important to add it in parenthesis in the current legend). The problem with using it as a description of the mode is that it doesn't tell you what the mode is doing or it's other properties (scope, precision, etc.) so for someone not familiar to Repograms you don't know what's happening. I'm not saying we should remove comparable/incomparable but it should be a complement to the description of the mode.

**Comment by daniboy** [comment]
@mpalyart @bestchai check the staging server:
http://repograms.net:8888/

I ended up adding 3 columns: not normalized at all, normalized by biggest project, and normalized individually (incomparable)
I also ended up adding the logarithmic view since it was very little extra work.

I haven't written the descriptions or chosen good names and icons, let me know what you think and if you're happy with this direction we can work on the presentation.

**Comment by mpalyart** [comment]
I'm not sure I really understand the difference of the new mode. Does normalized by biggest project not the same thing as not normalized at the minimum zoom?

**Comment by bestchai** [comment]
After playing around with it for a bit I think that Marc's description is correct -- normalized by biggest mode makes it fit on screen. The not normalized mode chooses some arbitrary value, it seems. These two seem very similar, unless we're both wrong..

**Comment by daniboy** [comment]
You're right, the left-most mode is basically an "unzoomed" version of the middle mode.
I created that mode because the top-left mode is equivalent to what used to be "Fixed", the middle-centre mode is equivalent to "Lines changed (comparable)" and the middle-right mode is equivalent to "Lines changed (incomparable)"

If we remove the left-most mode, we will lose this backwards compatibility. I agree that it's not a huge loss, since it can be achieved by switching to the top-centre mode and zooming.

What do you think?

**Comment by bestchai** [comment]
I think that the top-left 'fixed' commit block length is visually appealing. I would like to keep it some form. Here is one way -- make the top middle mode appear not in the most/least zoomed in view, but instead at whatever zoom level that corresponds to the fixed block length of the top left mode. This way, that block length is the default zoom level and is instantly accessible. But, if the user wants a more compressed view, then they can zoom out further.

**Comment by bestchai** [comment]
Agreed to drop the 'no normalization' column.

To fully resolve must also change the zoom-in level of the pre-made examples so that the ones that are using a fixed length are slightly zoomed in with normalization mode (to simulate what users saw in the study).

@daniboy will fix.

**Comment by daniboy** [comment]
@bestchai removed the "not normalized" mode, rotated the table (it looked very empty otherwise), fixed the hover issue. Check the staging server: http://repograms.net:8888/

I won't merge and deploy to the main server until we have the texts and icons ready (issue #99), we don't want a bunch of TODOs and meaningless icon all over :)
