### ISSUE TITLE
Feature request: Add author name to color.

### ISSUE THREAD

**Issue by whitecat** [RepoGrams/RepoGrams#92]
Similar to merging authors with multiple colors. 
You cannot identify what color belongs to what author.
Authors are identified only by number.

**Comment by whitecat** [comment]
Has this been pushed to the website yet? I  do not see author names on the website.

**Comment by whitecat** [comment]
I see that you made changes to add author which is amazing.
There is still the problem with multiple authors get different colors. Still with hugo. 
https://github.com/CPSC310-2014W2/Chitoge.git

Use the metric: "Commit Author"
Also recommend using Browse Length: "Fixed"
The same author has 3 colors. 
hugolee: Pink, Green
Hugo: Red

hugolee has the same e-mail just different name on 2 of his commits.

**Comment by whitecat** [comment]
Here are 2 commits different author color:
d627272ce99a6df3e2e2403cb4232da379936b69
d3f223ebbebed730c6cf06467314f141667f42e0

Both same e-mail: Author name is:
Hugo Lee <leehugo1994@gmail.com>
hugolee <leehugo1994@gmail.com>

**Comment by whitecat** [comment]
![screen shot 2015-04-23 at 4 40 50 pm](https://cloud.githubusercontent.com/assets/122229/7309775/8aa27f1a-e9d7-11e4-8ef0-7500f8f731de.png)
Blue is a small sliver. and Pink is huge but both should be the same color.

**Comment by daniboy** [comment]
I guess I can modify this metric to assign the same colour based on either the same name, or the same email address. I'll work on this tomorrow, shouldn't take too long.

**Comment by daniboy** [comment]
@whitecat updated in commit 2580173. Try the staging server again: http://repograms.net:8888/

**Comment by whitecat** [comment]
That broke the system. Everything is red now.

**Comment by daniboy** [comment]
It works for me (Firefox and Chrome), can you post the URLs that aren't working for you?
