### ISSUE TITLE
Bug: Size of commit is wrong

### ISSUE THREAD

**Issue by whitecat** [RepoGrams/RepoGrams#94]
The size of commit is actually byte size not lines changed.

**Comment by daniboy** [comment]
(working on branch: churn-fix)

Looks like I was mistaken yet again, it WAS working on Lines of Code, but it counted renamed files as deleted + added, I fixed that.

As for the other issue with merge commits, the API doesn't give me the option of creating a temporary merge and find how it changed. The way GitHub counts the churn of a merge commit is to diff it to the merged parents.

For example, if I am on branch `master` and there is another branch `other`, when I run `git merge other` GitHub will report how many additions/deletions happened to the current tip commit of `master` as if I created all the merged changes on that tip commit. See example: https://github.com/daniboy/private-test/commit/7825d94037567402021724e4dfd5b8f233ac3941

I'll follow their example here. Next up is to explore octopus merges (merges with more than 2 parents)

**Comment by daniboy** [comment]
Octopus merges seem to work on GitHub pretty much the same way, I didn't have to make any significant changes. I'll test this a bit and then merge to master and deploy to Jerry.

**Comment by whitecat** [comment]
The commits are still looking pretty huge on the repo. Is there a way to ignore images or large non code files?

**Comment by daniboy** [comment]
Binary files are ignored already, I'm afraid I can't think of a generic solution that won't break the view for other users of the tool
