### ISSUE TITLE
Export current state to JSON / import JSON to current state

### ISSUE THREAD

**Issue by daniboy** [RepoGrams/RepoGrams#96]

**Comment by daniboy** [comment]
@whitecat @bestchai I implemented the save/load feature. Check out the staging server. It's on the top-left corner next to the logo, where the "load examples" link used to be - now the load/save feature includes the samples as well.

Try it and let me know if it works: http://repograms.net:8888/

**Comment by whitecat** [comment]
@daniboy Works for me on Safari. I also tested the hide feature with this.
