### ISSUE TITLE
Show all the metrics' values in the modal popup

### ISSUE THREAD

**Issue by daniboy** [RepoGrams/RepoGrams#98]

**Comment by frankrui** [comment]
I'm not too clear on what this is means. Can you explain in more detail what you wanted this to look like? Thanks

**Comment by bestchai** [comment]
Here's the idea -- when you currently click on a commit in repograms you get a popup that shows you the commit id, and the commit message. This issue proposes to extend this popup window with a listing of the values for all of the currently displayed metrics. So, for the commit you clicked on you would be able to see a listing of all the corresponding metric values.

**Comment by frankrui** [comment]
So should the popup include all the currently selected metrics for this particular repo or all metrics in general. What should the format look like? Maybe "Metric name - value"?

**Comment by bestchai** [comment]
Yes, all currently selected metrics. Choose any format you like. We can iterate on it once you have a prototype.
